program        → declaration* EOF ;
declaration    → classDecl
               | funDecl
               | varDecl;

varDecl        → ("let"|typeExpr) IDENTIFIER  ( "=" expression )? ";" ;

typeExpr       →  IDENTIFIER([])?